### ISSUE TITLE
`--overwrite` configuration option not respected

### ISSUE THREAD

**Issue by djzager** [windup/rhamt-vscode-extension#728]
When attempting to run a configuration from the `MTA: Explorer` that has previously been run, I get the error:

```
time="2023-12-05T13:35:01-05:00" level=error msg="failed to validate flags" error="output dir /Users/dzager/.windup/tooling/vscode/2pkzd8cc9-7x3l4humx already exists and --overwrite not set"
```

Recreation Steps:
1. Activate the extension
2. Open the `MTA: Explorer` and create a new configuration
3. Run the configuration (cancel if you don't want to wait)
4. Select `--overwrite`
5. Run the configuration

Expected Results:
Analyzer to run

Actual Results:
```
time="2023-12-05T13:35:01-05:00" level=error msg="failed to validate flags" error="output dir /Users/dzager/.windup/tooling/vscode/2pkzd8cc9-7x3l4humx already exists and --overwrite not set"
```

**Comment by hhpatel14** [comment]
https://github.com/windup/rhamt-vscode-extension/blob/65bc7912aba4819d4fdc9e6c325ac4cedc52c6f6/src/server/analyzerUtil.ts#L121 The buildParam method currently does not check for the --overwrite flag. Although the UI includes --overwrite as an option, it doesn't get parsed. Kantra sets --overwrite to false by default. Therefore, we need to add a logic condition: 'if the output path exists and is not empty,' then we should include the --overwrite flag. https://github.com/konveyor/kantra/blob/e35c2bdca132fdd36e6edfd00b4c4c82e63e74b9/cmd/analyze.go#L244
